Repository ivbo-05-18/mirea_course, pull requests merged in 2020-06, with the labels that each got.

#7 Oleynikov ap
  src/App.js
  src/components/OleynikovAP/OleynikovAPController.js
  src/components/OleynikovAP/OleynikovAPElement.js
  src/components/OleynikovAP/components/Input/Input.js
  src/components/OleynikovAP/components/Kramer/Kramer.js
  src/components/OleynikovAP/components/Kramer/Kramer.test.js
  src/components/OleynikovAP/components/Kramer/slauResult.js
  src/components/OleynikovAP/components/Matrix/Matrix.js
  src/components/OleynikovAP/components/Sweeper/App.js
  src/components/OleynikovAP/hoc/ToggleElem/ToggleElem.js
Labels: Checked by maintainers, Ok

#9 Velikanov ky personal branch
  .env
  package-lock.json
  package.json
  src/App.js
  src/components/VelikanovKY/KlevleevVRToDo.js
  src/components/VelikanovKY/KlevleevVRToDoForm.js
  src/components/VelikanovKY/KlevleevVRToDoList.js
  src/components/VelikanovKY/KlevleevlVRToDoListItem.js
  src/components/VelikanovKY/Trends.js
  src/components/VelikanovKY/VelikanovKYController.js
  src/components/VelikanovKY/VelikanovKYElement.js
  src/components/VelikanovKY/Weather.js
  src/components/VelikanovKY/WindDirection.js
  src/components/VelikanovKY/__tests__/Weather.test.js
  src/components/VelikanovKY/__tests__/__snapshots__/Weather.test.js.snap
Labels: Checked by maintainers, Ok

#13 Ivanov D.S.
  .github/workflows/main.yml
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/TicTacToe.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
  src/App.js
  src/components/IvanovDS/Gifs/Cats.js
  src/components/IvanovDS/Gifs/Gifs.js
  src/components/IvanovDS/Gifs/Gifs.module.css
  src/components/IvanovDS/Gifs/getRandom.js
  src/components/IvanovDS/IvanovDSController.js
  src/components/IvanovDS/IvanovDSElement.js
  src/components/IvanovDS/SimonSays/SimonSays.js
  src/components/IvanovDS/SimonSays/SimonSays.module.css
  src/components/IvanovDS/TicTacToe/TicTacToe.js
  src/components/IvanovDS/TicTacToe/TicTacToe.module.css
  src/components/IvanovDS/index.js
Labels: Checked by maintainers, Ok

#14 Miroshnik g.k
  package-lock.json
  package.json
  src/App.js
  src/components/MiroshnikGK/Color.js
  src/components/MiroshnikGK/Color/Field.js
  src/components/MiroshnikGK/Color/Square.js
  src/components/MiroshnikGK/Color/hextocmyk.js
  src/components/MiroshnikGK/MiroshnikGKController.js
  src/components/MiroshnikGK/MiroshnikGKElement.js
  src/components/MiroshnikGK/integrations/WithMoveValidation.js
  src/components/MiroshnikGK/tests/CMYK.test.js
  src/components/MiroshnikGK/tests/Color.test.js
  src/components/MiroshnikGK/tests/Field.test.js
  src/components/MiroshnikGK/tests/Square.test.js
  src/components/MiroshnikGK/tests/__snapshots__/Color.test.js.snap
  src/components/MiroshnikGK/tests/__snapshots__/Field.test.js.snap
  src/components/MiroshnikGK/tests/__snapshots__/Square.test.js.snap
Labels: Checked by maintainers, Ok

#15 Klevleev_VR
  .env
  src/App.js
  src/components/KlevleevVR/ColorFood/ColorFood.js
  src/components/KlevleevVR/ColorFood/Graph.js
  src/components/KlevleevVR/ColorFood/components/Cell/Cell.js
  src/components/KlevleevVR/ColorFood/components/Cell/Cell.module.css
  src/components/KlevleevVR/ColorFood/components/ColorPickers/ColorPickers.js
  src/components/KlevleevVR/ColorFood/components/ColorPickers/ColorPickers.module.css
  src/components/KlevleevVR/ColorFood/components/Grid/Grid.js
  src/components/KlevleevVR/ColorFood/components/Grid/Grid.module.css
  src/components/KlevleevVR/ColorFood/components/Picker/Picker.js
  src/components/KlevleevVR/ColorFood/components/Picker/Picker.module.css
  src/components/KlevleevVR/ColorFood/favicon.ico
  src/components/KlevleevVR/ColorFood/index.module.css
  src/components/KlevleevVR/GuessTheSong.js
  src/components/KlevleevVR/GuessTheSong.test.js
  src/components/KlevleevVR/KlevleevVRController.js
  src/components/KlevleevVR/KlevleevVRElement.js
  src/components/KlevleevVR/Result.js
  src/components/KlevleevVR/SpacePeople/SpacePeople.js
  src/components/KlevleevVR/SpacePeople/SpacePeople.test.js
  src/components/KlevleevVR/SpacePeople/__snapshots__/SpacePeople.test.js.snap
Labels: Checked by maintainers, Ok

#17 Murashev as
  .eslintrc.json
  src/App.js
  src/components/MurashevAS/components.js
  src/components/MurashevAS/controller.js
  src/components/MurashevAS/mon_change/money.js
  src/components/MurashevAS/mon_change/money.test.js
  src/components/MurashevAS/mon_change/moneychange.js
  src/components/MurashevAS/mon_change/moneywork.js
  src/components/MurashevAS/mon_change/super_duper_key.js
  src/components/MurashevAS/ping-pong/ping-pong.js
  src/components/MurashevAS/ping-pong/ping-pong_app.js
  src/components/MurashevAS/ping-pong/pp_style.module.css
Labels: Checked by maintainers, Ok

#18 Kapyrin ka
  package.json
  src/App.js
  src/components/KapyrinKA/Element.module.css
  src/components/KapyrinKA/EmojiesList/App.js
  src/components/KapyrinKA/EmojiesList/EmojiResultRow.css
  src/components/KapyrinKA/EmojiesList/EmojiResultRow.js
  src/components/KapyrinKA/EmojiesList/EmojiResults.js
  src/components/KapyrinKA/EmojiesList/Header.js
  src/components/KapyrinKA/EmojiesList/Header.module.css
  src/components/KapyrinKA/EmojiesList/SearchInput.js
  src/components/KapyrinKA/EmojiesList/SearchInput.module.css
  src/components/KapyrinKA/EmojiesList/emojiList.json
  src/components/KapyrinKA/EmojiesList/filterEmoji.js
  src/components/KapyrinKA/KapyrinKAcontroller.js
  src/components/KapyrinKA/KapyrinKAelement.js
  src/components/KapyrinKA/mon_change/money.js
  src/components/KapyrinKA/mon_change/money.test.js
  src/components/KapyrinKA/mon_change/moneychange.js
  src/components/KapyrinKA/mon_change/moneywork.js
  src/components/KapyrinKA/mon_change/super_duper_key.js
  src/components/KapyrinKA/my-gifs/Gifs.js
  src/components/KapyrinKA/my-gifs/Gifs.module.css
  src/components/KapyrinKA/my-gifs/SecondGifs.js
  src/components/KapyrinKA/my-gifs/SecondGifs.test.js
  src/components/KapyrinKA/my-gifs/getRandom.js
Labels: Checked by maintainers, Ok

#23 Vesyolkin_AS
  src/App.js
  src/components/VesyolkinAS/React-Sweeper-master/README.md
  src/components/VesyolkinAS/React-Sweeper-master/src/App.js
  src/components/VesyolkinAS/React-Sweeper-master/src/Minesweeper.module.css
  src/components/VesyolkinAS/React-Sweeper-master/src/serviceWorker.js
  src/components/VesyolkinAS/VesyolkinASController.jsx
  src/components/VesyolkinAS/VesyolkinASElement.jsx
  src/components/VesyolkinAS/converter/__snapshots__/converter.test.js.snap
  src/components/VesyolkinAS/converter/converter-logic.test.js
  src/components/VesyolkinAS/converter/converter-logik.jsx
  src/components/VesyolkinAS/converter/converter.jsx
  src/components/VesyolkinAS/converter/converter.test.js
Labels: Checked by maintainers, Ok

#24 Корнеев Д.С.
  .eslintignore
  src/App.js
  src/components/KorneevDS/KorneevDSController.js
  src/components/KorneevDS/KorneevDSElement.js
  src/components/KorneevDS/index.js
  src/components/KorneevDS/react-tic-tac-toe/Board.js
  src/components/KorneevDS/react-tic-tac-toe/Game.js
  src/components/KorneevDS/react-tic-tac-toe/Square.js
  src/components/KorneevDS/react-tic-tac-toe/TicTacToe.module.css
  src/components/KorneevDS/react-tic-tac-toe/index.js
  src/components/KorneevDS/watch/watch.js
Labels: Ok, WIP

#25 Kuzmin
  .eslintignore
  package.json
  src/App.js
  src/components/KuzminLO/KuzminLOController.js
  src/components/KuzminLO/KuzminLOElement.js
  src/components/KuzminLO/__tests__/corona.test.js
  src/components/KuzminLO/coronatime.js
  src/components/KuzminLO/konvertilo-master/src/app/app.js
  src/components/KuzminLO/konvertilo-master/src/app/app.json
  src/components/KuzminLO/konvertilo-master/src/app/binary.js
  src/components/KuzminLO/konvertilo-master/src/app/decimal.js
  src/components/KuzminLO/konvertilo-master/src/styles/styles.js
  src/components/KuzminLO/styles.js
Labels: Checked by maintainers, Ok

#26 Veselaya E.A.
  .env
  package.json
  src/App.js
  src/components/VeselayaEA/Currency.js
  src/components/VeselayaEA/VeselayaEAController.js
  src/components/VeselayaEA/VeselayaEAElement.js
Labels: Ok, WIP

#27 PerederiyVA
  src/components/PerederiyVA/Gauss/GaussianElimElement.css
  src/components/PerederiyVA/Gauss/GaussianElimElement.js
  src/components/PerederiyVA/Gauss/GaussianElimElement.module.css
  src/components/PerederiyVA/Gauss/GaussianElimResult.js
  src/components/PerederiyVA/PerederiyVAController.js
  src/components/PerederiyVA/PerederiyVAElement.js
  src/components/PerederiyVA/Snake/lib/components/Board.js
Labels: Checked by maintainers, Ok

#28 KomarBG course work
  .env
  .gitignore
  package.json
  src/App.js
  src/components/KomarBG/DinoGame/Dino.js
  src/components/KomarBG/DinoGame/DinoScript.js
  src/components/KomarBG/DinoGame/DinoStyle.js
  src/components/KomarBG/DinoGame/README.md
  src/components/KomarBG/DinoGame/Resources.js
  src/components/KomarBG/DinoGame/index.js
  src/components/KomarBG/KomarBGController.js
  src/components/KomarBG/KomarBGElement.js
  src/components/KomarBG/MemeCreator/Meme.js
  src/components/KomarBG/MemeCreator/MemeCreator.js
  src/components/KomarBG/MemeCreator/MemeEditor.js
Labels: Checked by maintainers, Ok

#30 Burin IS
  .eslintignore
  src/App.js
  src/components/BurinIS/BurinISController.js
  src/components/BurinIS/BurinISElement.js
  src/components/BurinIS/GithubModule/konvertilo-master/src/app/app.js
  src/components/BurinIS/GithubModule/konvertilo-master/src/app/app.json
  src/components/BurinIS/GithubModule/konvertilo-master/src/app/binary.js
  src/components/BurinIS/GithubModule/konvertilo-master/src/app/decimal.js
  src/components/BurinIS/GithubModule/konvertilo-master/src/styles/styles.js
  src/components/BurinIS/Solver.css
  src/components/BurinIS/Solver.js
  src/components/BurinIS/Solver.test.js
  src/components/BurinIS/__snapshots__/Solver.test.js.snap
  src/components/BurinIS/calculate.js
  src/components/BurinIS/calculate.test.js
Labels: Checked by maintainers, Ok

#31 VyrupaevaMA
  package.json
  src/App.js
  src/components/VyrupaevaMA/Borrowed/App.test.js
  src/components/VyrupaevaMA/Borrowed/Dice.module.css
  src/components/VyrupaevaMA/Borrowed/DiceRoller.js
  src/components/VyrupaevaMA/Borrowed/Die.js
  src/components/VyrupaevaMA/Mate/plus.png
  src/components/VyrupaevaMA/Mate/pokemon.js
  src/components/VyrupaevaMA/Mate/pokemon.module.css
  src/components/VyrupaevaMA/Mate/pokemon_main.js
  src/components/VyrupaevaMA/Mate/sword.png
  src/components/VyrupaevaMA/Sentences/Sentences.css
  src/components/VyrupaevaMA/Sentences/Sentences.js
  src/components/VyrupaevaMA/Sentences/Sentences.test.js
  src/components/VyrupaevaMA/Sentences/__snapshots__/Sentences.test.js.snap
  src/components/VyrupaevaMA/Sentences/getResult.js
  src/components/VyrupaevaMA/VyrupaevaMAController.js
  src/components/VyrupaevaMA/VyrupaevaMAElement.js
  src/components/VyrupaevaMA/index.js
Labels: Ok, WIP

#32 Tarasov_AA
  package.json
  src/App.js
  src/components/TarasovAA/Clock/Clock.js
  src/components/TarasovAA/Color/Color.js
  src/components/TarasovAA/Color/Field.js
  src/components/TarasovAA/Color/Square.js
  src/components/TarasovAA/Color/hextocmyk.js
  src/components/TarasovAA/Greetings/Flag.js
  src/components/TarasovAA/Greetings/ForeignGreetings.js
  src/components/TarasovAA/Greetings/Hello.js
  src/components/TarasovAA/TarasovAAController.js
  src/components/TarasovAA/TarasovAAElement.js
Labels: Ok, WIP

#33 Bekina mp
  package.json
  src/App.js
  src/components/BekinaMP/BekinaMPController.js
  src/components/BekinaMP/BekinaMPElement.js
  src/components/BekinaMP/TextTransformer.js
  src/components/BekinaMP/__test__/TextTranformer.test.js
Labels: Ok, WIP

#37 Medny NY
  .eslintignore
  package.json
  src/App.js
  src/components/MednyNY/Calculator/components/Display.js
  src/components/MednyNY/Calculator/components/Key.js
  src/components/MednyNY/Calculator/index.js
  src/components/MednyNY/Calculator/style.module.css
  src/components/MednyNY/Forecast/WeatherInfo.js
  src/components/MednyNY/Forecast/__snapshots__/weather.test.js.snap
  src/components/MednyNY/Forecast/__snapshots__/weather2.test.js.snap
  src/components/MednyNY/Forecast/weather.js
  src/components/MednyNY/Forecast/weather.module.css
  src/components/MednyNY/Forecast/weather.test.js
  src/components/MednyNY/Forecast/weather1.test.js
  src/components/MednyNY/Forecast/weather2.test.js
  src/components/MednyNY/Ghibli/About.js
  src/components/MednyNY/Ghibli/Change.js
  src/components/MednyNY/Ghibli/Ghibli_Elem.js
  src/components/MednyNY/Ghibli/index.js
  src/components/MednyNY/MednyNYController.js
  src/components/MednyNY/MednyNYElement.js
  src/components/MednyNY/index.js
Labels: Ok, WIP

#38 Mironova aa
  .env
  package.json
  src/App.js
  src/components/MironovaAA/MironovaAAController.js
  src/components/MironovaAA/MironovaAAElement.js
  src/components/MironovaAA/nekotube/components/Body/Body.js
  src/components/MironovaAA/nekotube/components/Header/Header.js
  src/components/MironovaAA/nekotube/components/Video/Item/Item.js
  src/components/MironovaAA/nekotube/components/Video/List/List.js
  src/components/MironovaAA/nekotube/components/Video/Video.js
  src/components/MironovaAA/nekotube/nekotube.js
Labels: Ok
